fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black LR2-5/app/src
        language: system
        pass_filenames: false
        types: [python]

      - id: isort
        name: isort
        entry: isort LR2-5/app/src
        language: system
        pass_filenames: false
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint LR2-5/app/src
        language: system
        pass_filenames: false
        types: [python]